### ISSUE TITLE
Selected items are cleared when switching between filtered views.

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-select-field#53] opened 2019-11-26 13:48 UTC
### Expected behavior
Selected items to remain selected when switching between filter views.

### Actual behavior
When switching between filter views, all selections are cleared.
 
### Steps to reproduce
In the demo at https://developer.blackbaud.com/skyux/components/select-field, select the Select fruits button. Select all the items in the list. Then select the Filter button and select an option in the filter. All items items in the filtered list are no longer selected. Select Show all in the filter dropdown. All items in the list are no longer selected. ... The same thing happens if you select items in any filtered view and then switch to another view.

**Comment by Blackbaud-AlexKingman** [comment] 2019-12-03 15:42
It looks like this is expected behavior (or at least it was when it was initially built):
https://github.com/blackbaud/skyux-select-field/blob/master/src/app/public/modules/select-field/select-field-picker.component.ts#L117

Does it still make sense to clear selections every time the category filter changes?

**Comment by Blackbaud-AlexKingman** [comment] 2019-12-04 20:59
After some discussion with the group, this was done to avoid a user inadvertently taking action on things that might be "selected" but hidden due to the filter setting. This is not a bug, but the expected behavior for select-field. Closing.

**Closed by Blackbaud-AlexKingman** 2019-12-04 20:59 UTC
Labels: From: Consumer, Impact: Medium, Needs: More info, Severity: High, Type: Bug
